# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Warm up git 🔥
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git config pull.rebase false
        git pull --allow-unrelated-histories origin gh-pages
    - run: npm ci
    - run: npm run build
    - name: Deploying
      run: |
        git add dist/
        git checkout gh-pages
        git commit -m 'Add pages'
        git push -u origin gh-pages
